SELECT B.SEASON, SUM(B.SALARY), COUNT(*), AVG(B.SALARY)
	FROM PROFILEF A, SALARY B 
	WHERE A.PLAYERID = B.PLAYERID
	AND A.PLAYERID IN (SELECT PLAYERID
							FROM ACTIVEPLAYERS
		   					WHERE ACTIVE = "TRUE")
	GROUP BY SEASON;