SELECT A.SEASON, B.TEAM_id, A.TEAM, AVG(A.SALARY) AS AVGSALARY
	FROM SALARY A, TEAMMAP B
	WHERE B.TEAM_NAME = A.TEAM
		AND A.SEASON BETWEEN 2002
		AND 2011
	GROUP BY A.TEAM, A.SEASON;

WITH map AS (SELECT SEASON, TEAM, SUM((SALARY-(SELECT AVG(SALARY)
													FROM SALARY
													WHERE SEASON BETWEEN 2002 AND 2011)) * (SALARY-(SELECT AVG(SALARY)
																										FROM SALARY
																										WHERE SEASON BETWEEN 2002 AND 2011))) / (COUNT(SALARY)-1) AS VARIANCE
				FROM SALARY
				WHERE SEASON BETWEEN 2002 AND 2011
				GROUP BY TEAM, SEASON)
	SELECT a.season, b.team_id, a.team, a.variance
		FROM map a, teammap b
		WHERE a.team = b.team_name;